name: Django CI

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: sudo docker-compose -f docker-compose.yml up

  test:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Analysing the code with pylint
      run: >
        docker-compose -u root -f docker-compose.yml run web python 
        $(which pylint) --fail-under=${{vars.PYLINT_THRESHOLD}} $(git ls-files '*.py')
    - name: Run Django Tests
      run: |
        docker-compose -f docker-compose.yml run web python mysite/manage.py test
        echo $TEST
