name: Django CI

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: sudo docker-compose -f docker-compose.yml up

  test:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Analysing the code with pylint
      run: >
        sudo docker-compose run web pylint --fail-under=5 $(git ls-files '*.py')
    - name: Run Django Tests
      run: |
        sudo docker-compose run web python mysite/manage.py test
        echo $TEST
