name: Django CI

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: sudo docker-compose -f docker-compose.yml build

  test:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Run Django Tests
        run: |
          sudo docker-compose run web python mysite/manage.py test polls
          echo $TEST

      - name: Analysing the code with pylint
        run: >
          sudo docker-compose run --rm web pylint --fail-under=5 $(git ls-files '*.py')
          

  push:
    needs: test
    runs-on: self-hosted
    steps:
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push devops_web:latest
